name: Update Users JSON

on:
  schedule:
    - cron: '0 0 * * *'  # codziennie o 00:00 UTC
  workflow_dispatch:      # pozwala ręczne uruchomienie

jobs:
  update-users:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        run: |
          python fetch_users.py  # Twój skrypt pobierający JSON i zapisujący do users.json
       - name: Commit changes
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add users.json
          git commit -m "Automatyczna aktualizacja users.json: $(date '+%Y-%m-%d %H:%M:%S')" || echo "Brak zmian do commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     
